version: '3.8'
services:

    frontend:
      build:
        context: ./frontend 
      ports:
        - "3000:3000"
      networks:
        - app-network
    web:
      image: nginx:alpine
      container_name: laravel-nginx
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./laravel:/var/www/html
        - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - app
      networks:
        - app-network

    app:
      build:
        context: ./backend 
      ports:
        - "8000:8000"
      container_name: laravel-app
      restart: always
      working_dir: /app
      volumes:
        - ./:/var/www/html
      depends_on:
        - mysql
      networks:
        - app-network

    mysql:
      image: mysql:5.7
      restart: unless-stopped
      environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: aggregator
      volumes:
        - ./initdb:/docker-entrypoint-initdb.d
      ports:
        - 3306:3306
      networks:
        - app-network

networks:
  app-network:
    driver: bridge